pub mod commands;
pub mod db;
pub mod models;

use tauri::Manager;
use tauri_specta::{collect_commands, Builder};

use crate::db::Db;

#[cfg_attr(mobile, tauri::mobile_entry_point)]
pub fn run() {
    let builder = Builder::<tauri::Wry>::new().commands(collect_commands![
        commands::create_tag,
        commands::save_tag,
        commands::get_tag,
        commands::list_tags,
        commands::delete_tag,
        commands::create_task,
        commands::save_task,
        commands::get_task,
        commands::list_tasks,
        commands::delete_task,
        commands::create_project,
        commands::save_project,
        commands::get_project,
        commands::list_projects,
        commands::delete_project,
        commands::create_note,
        commands::save_note,
        commands::get_note,
        commands::list_notes,
        commands::delete_note,
        commands::create_graph,
        commands::save_graph,
        commands::get_graph,
        commands::list_graphs,
        commands::delete_graph,
        commands::create_calendar,
        commands::save_calendar,
        commands::get_calendar,
        commands::list_calendars,
        commands::delete_calendar,
        commands::create_recurrence,
        commands::save_recurrence,
        commands::get_recurrence,
        commands::list_recurrences,
        commands::delete_recurrence,
        commands::create_feed_source,
        commands::save_feed_source,
        commands::get_feed_source,
        commands::list_feed_sources,
        commands::delete_feed_source,
        commands::create_user,
        commands::save_user,
        commands::get_user,
        commands::list_users,
        commands::delete_user,
        commands::get_or_create_current_user,
    ]);

    // In debug builds (i.e. `cargo tauri dev`), regenerate src/bindings.ts so
    // the TypeScript types stay in sync with the Rust command signatures.
    #[cfg(debug_assertions)]
    builder
        .export(
            specta_typescript::Typescript::default()
                .header("/* eslint-disable */\n// This file is auto-generated by tauri-specta. Do not edit manually."),
            "../src/bindings.ts",
        )
        .expect("Failed to export TypeScript bindings");

    tauri::Builder::default()
        .plugin(tauri_plugin_opener::init())
        .setup(|app| {
            let data_dir = app.path().app_data_dir()?;
            std::fs::create_dir_all(&data_dir)?;
            let db = Db::new(data_dir.join("explorer.db"))?;
            app.manage(db);
            Ok(())
        })
        .invoke_handler(builder.invoke_handler())
        .run(tauri::generate_context!())
        .expect("error while running tauri application");
}
