/* eslint-disable */
// This file is auto-generated by tauri-specta. Do not edit manually.
// This file was generated by [tauri-specta](https://github.com/oscartbeaumont/tauri-specta). Do not edit this file manually.

/** user-defined commands **/


export const commands = {
async createTag(label: string, color: string | null) : Promise<Result<Tag, DbError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("create_tag", { label, color }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async saveTag(tag: Tag) : Promise<Result<null, DbError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("save_tag", { tag }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getTag(id: string) : Promise<Result<Tag, DbError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_tag", { id }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async listTags() : Promise<Result<Tag[], DbError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("list_tags") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async deleteTag(id: string) : Promise<Result<null, DbError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("delete_tag", { id }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async createTask(title: string, description: string) : Promise<Result<Task, DbError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("create_task", { title, description }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async saveTask(task: Task) : Promise<Result<null, DbError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("save_task", { task }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getTask(id: string) : Promise<Result<Task, DbError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_task", { id }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async listTasks() : Promise<Result<Task[], DbError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("list_tasks") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async deleteTask(id: string) : Promise<Result<null, DbError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("delete_task", { id }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async createProject(title: string, description: string) : Promise<Result<Project, DbError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("create_project", { title, description }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async saveProject(project: Project) : Promise<Result<null, DbError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("save_project", { project }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getProject(id: string) : Promise<Result<Project, DbError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_project", { id }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async listProjects() : Promise<Result<Project[], DbError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("list_projects") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async deleteProject(id: string) : Promise<Result<null, DbError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("delete_project", { id }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async createNote(title: string) : Promise<Result<Note, DbError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("create_note", { title }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async saveNote(note: Note) : Promise<Result<null, DbError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("save_note", { note }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getNote(id: string) : Promise<Result<Note, DbError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_note", { id }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async listNotes() : Promise<Result<Note[], DbError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("list_notes") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async deleteNote(id: string) : Promise<Result<null, DbError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("delete_note", { id }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async createGraph(title: string, description: string) : Promise<Result<Graph, DbError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("create_graph", { title, description }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async saveGraph(graph: Graph) : Promise<Result<null, DbError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("save_graph", { graph }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getGraph(id: string) : Promise<Result<Graph, DbError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_graph", { id }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async listGraphs() : Promise<Result<Graph[], DbError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("list_graphs") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async deleteGraph(id: string) : Promise<Result<null, DbError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("delete_graph", { id }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async createCalendar(name: string) : Promise<Result<Calendar, DbError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("create_calendar", { name }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async saveCalendar(calendar: Calendar) : Promise<Result<null, DbError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("save_calendar", { calendar }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getCalendar(id: string) : Promise<Result<Calendar, DbError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_calendar", { id }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async listCalendars() : Promise<Result<Calendar[], DbError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("list_calendars") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async deleteCalendar(id: string) : Promise<Result<null, DbError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("delete_calendar", { id }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async createRecurrence() : Promise<Result<RecurrenceRule, DbError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("create_recurrence") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async saveRecurrence(rule: RecurrenceRule) : Promise<Result<null, DbError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("save_recurrence", { rule }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getRecurrence(id: string) : Promise<Result<RecurrenceRule, DbError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_recurrence", { id }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async listRecurrences() : Promise<Result<RecurrenceRule[], DbError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("list_recurrences") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async deleteRecurrence(id: string) : Promise<Result<null, DbError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("delete_recurrence", { id }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async createFeedSource(name: string, baseUrl: string) : Promise<Result<FeedSource, DbError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("create_feed_source", { name, baseUrl }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async saveFeedSource(source: FeedSource) : Promise<Result<null, DbError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("save_feed_source", { source }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getFeedSource(id: string) : Promise<Result<FeedSource, DbError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_feed_source", { id }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async listFeedSources() : Promise<Result<FeedSource[], DbError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("list_feed_sources") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async deleteFeedSource(id: string) : Promise<Result<null, DbError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("delete_feed_source", { id }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async createUser() : Promise<Result<User, DbError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("create_user") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async saveUser(user: User) : Promise<Result<null, DbError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("save_user", { user }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getUser(id: string) : Promise<Result<User, DbError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_user", { id }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async listUsers() : Promise<Result<User[], DbError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("list_users") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async deleteUser(id: string) : Promise<Result<null, DbError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("delete_user", { id }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getOrCreateCurrentUser() : Promise<Result<User, DbError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_or_create_current_user") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
}
}

/** user-defined events **/



/** user-defined constants **/



/** user-defined types **/

export type BlockType = "text" | "drawing" | "image" | "embed"
export type Calendar = { id: string; created_at: string; updated_at: string; calendar_events: CalendarEvent[]; name: string; color: string | null; is_visible: boolean; is_default: boolean }
export type CalendarEvent = { id: string; created_at: string; updated_at: string; recurrence_id: string | null; calendar_id: string | null; title: string; description: string; start_datetime: string | null; end_datetime: string | null; is_all_day: boolean; location: string | null; color: string | null }
export type Connection = { id: string; created_at: string; updated_at: string; source_node_id: string | null; dest_node_id: string | null; label: ConnectionLabel | null; is_directed: boolean }
export type ConnectionLabel = "relates_to" | "caused_by" | "is_a" | "uses"
export type DayOfWeek = "monday" | "tuesday" | "wednesday" | "thursday" | "friday" | "saturday" | "sunday"
export type DbError = { Sqlite: string } | "NotFound" | { Migration: string }
export type DefaultView = "graph" | "feed" | "tasks" | "notes" | "calendar"
export type Features = { id: string; created_at: string; updated_at: string; knowledge_graph_enabled: boolean; notes_whiteboard_enabled: boolean; tasks_enabled: boolean; calendar_enabled: boolean; feed_enabled: boolean; notes_enabled: boolean }
export type FeedInterest = { id: string; created_at: string; updated_at: string; last_interacted_at: string | null; topic: string; sources: FeedSource[]; explicit_weight: number | null; open_count: number; save_count: number; dismiss_count: number }
export type FeedSource = { id: string; created_at: string; updated_at: string; source_type: SourceType | null; name: string; base_url: string; is_enabled: boolean; requires_key: boolean }
export type Frequency = "daily" | "weekly" | "monthly" | "yearly"
export type Graph = { id: string; created_at: string; updated_at: string; nodes: Node[]; connections: Connection[]; title: string; description: string }
export type Node = { id: string; created_at: string; updated_at: string; node_type: NodeType; x: number; y: number; title: string; content: string; tags: Tag[] }
export type NodeType = "file" | "video" | "audio" | "text" | "image"
export type Note = { id: string; created_at: string; updated_at: string; note_blocks: NoteBlock[]; title: string; is_pinned: boolean; tags: Tag[] }
export type NoteBlock = { id: string; created_at: string; updated_at: string; note_id: string | null; block_type: BlockType | null; content: string; position: number | null }
export type Preferences = { id: string; created_at: string; updated_at: string; feed_interests: FeedInterest[]; display_name: string; theme: Theme; accent_color: string | null; features: Features; sidebar_collapsed: boolean; default_view: DefaultView }
export type Priority = "low" | "medium" | "high" | "urgent"
export type Project = { id: string; created_at: string; updated_at: string; tasks: Task[]; is_archived: boolean; title: string; description: string; color: string | null; tags: Tag[] }
export type RecurrenceRule = { id: string; created_at: string; updated_at: string; frequency: Frequency | null; interval: number | null; days_of_week: DayOfWeek[]; day_of_month: number | null; end_date: string | null }
export type SourceType = "text" | "image" | "video" | "audio"
export type Status = "todo" | "in_progress" | "done" | "cancelled"
export type Tag = { id: string; created_at: string; updated_at: string; label: string; color: string | null }
export type Task = { id: string; created_at: string; updated_at: string; recurrence_id: string | null; parent_id: string | null; project_id: string | null; completed_at: string | null; title: string; description: string; status: Status | null; priority: Priority | null; due_date: string | null; tags: Tag[] }
export type Theme = "light" | "dark"
export type User = { id: string; created_at: string; updated_at: string; preferences: Preferences }

/** tauri-specta globals **/

import {
	invoke as TAURI_INVOKE,
	Channel as TAURI_CHANNEL,
} from "@tauri-apps/api/core";
import * as TAURI_API_EVENT from "@tauri-apps/api/event";
import { type WebviewWindow as __WebviewWindow__ } from "@tauri-apps/api/webviewWindow";

type __EventObj__<T> = {
	listen: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.listen<T>>;
	once: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.once<T>>;
	emit: null extends T
		? (payload?: T) => ReturnType<typeof TAURI_API_EVENT.emit>
		: (payload: T) => ReturnType<typeof TAURI_API_EVENT.emit>;
};

export type Result<T, E> =
	| { status: "ok"; data: T }
	| { status: "error"; error: E };

function __makeEvents__<T extends Record<string, any>>(
	mappings: Record<keyof T, string>,
) {
	return new Proxy(
		{} as unknown as {
			[K in keyof T]: __EventObj__<T[K]> & {
				(handle: __WebviewWindow__): __EventObj__<T[K]>;
			};
		},
		{
			get: (_, event) => {
				const name = mappings[event as keyof T];

				return new Proxy((() => {}) as any, {
					apply: (_, __, [window]: [__WebviewWindow__]) => ({
						listen: (arg: any) => window.listen(name, arg),
						once: (arg: any) => window.once(name, arg),
						emit: (arg: any) => window.emit(name, arg),
					}),
					get: (_, command: keyof __EventObj__<any>) => {
						switch (command) {
							case "listen":
								return (arg: any) => TAURI_API_EVENT.listen(name, arg);
							case "once":
								return (arg: any) => TAURI_API_EVENT.once(name, arg);
							case "emit":
								return (arg: any) => TAURI_API_EVENT.emit(name, arg);
						}
					},
				});
			},
		},
	);
}
